smartbook/smartbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('web.urls')),
	url(r'^purchase/', include('purchase.urls')),
	url(r'^sales/', include('sales.urls')),
	url(r'^inventory/', include('inventory.urls')),
	url(r'^reports/', include('reports.urls')),
	url(r'^expenses/', include('expenses.urls')),
)

smartbook/web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from django.conf import settings

from web.views import *

urlpatterns = patterns('',
	url(r'^$', Home.as_view(), name='home'),
	url(r'login/$', Login.as_view(), name='login'),
	url(r'logout/$', login_required(Logout.as_view()), name='logout'),
	url(r'^register/(?P<user_type>\w+)/$', login_required(RegisterUser.as_view()), name='register_user'),
	url(r'^register/salesman/(?P<user_type>\w+)/$', login_required(RegisterSalesman.as_view()), name='register_salesman'),
	url(r'^(?P<user_type>\w+)/list/$', login_required(UserList.as_view()), name='users'),
	url(r'^(?P<user_type>\w+)/(?P<user_id>\d+)/edit/$', login_required(EditUser.as_view()), name='edit_user'),
	url(r'^(?P<user_type>\w+)/(?P<user_id>\d+)/delete/$', login_required(DeleteUser.as_view()), name='delete_user'),
	url(r'^company_list/$', login_required(TransportationCompanyList.as_view()), name="company_list"),
	url(r'^add_company/$', login_required(AddTransportationCompany.as_view()), name="add_company"),
	url(r'^reset_password/(?P<user_id>\d+)/$', login_required(ResetPassword.as_view()), name="reset_password"),
	url(r'^backup/$', login_required(BackupView.as_view()), name="backup"),
	url(r'^clear_backup/$', login_required(ClearBackup.as_view()), name="clear_backup"),
	url(r'^backups/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	url(r'^create_customer/$', login_required(CreateCustomer.as_view()), name='create_customer'),
)

smartbook/web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

USER_TYPE = (
    ('vendor', 'Vendor'),
    ('customer', 'Customer'),
    ('Salesman','Salesman')
)

class UserProfile(models.Model):
    user = models.ForeignKey(User)
    user_type = models.CharField('User Type', max_length=10, choices=USER_TYPE)
    house_name = models.CharField('House name', null=True, blank=True, max_length=50)
    street = models.CharField('Street', null=True, blank=True, max_length=50)
    city = models.CharField('City', null=True, blank=True, max_length=50)
    district = models.CharField('District', null=True, blank=True, max_length=50)
    pin = models.CharField('Pin', max_length=10, null=True, blank=True,)
    mobile = models.CharField('Mobile', max_length=15, null=True, blank=True)
    land_line = models.CharField('Land Line',max_length=15, blank=True)
    email_id = models.CharField('Email Id', max_length=30)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profile'

class Vendor(models.Model):
    user = models.ForeignKey(User)
    contact_person = models.CharField('Contact Person', max_length=50)  

    def save(self, *args, **kwargs):
        profile = self.user.userprofile_set.all()
        if len(profile) == 0:
            profile = UserProfile.objects.create(user = self.user)
        super(Vendor, self).save(*args, **kwargs)

    def __unicode__(self):
        return "vendor - "+self.user.first_name
    

    class Meta:

        verbose_name = 'Vendor'
        verbose_name_plural = 'Vendor'

    
class Customer(models.Model):
    
    customer_name = models.CharField('Name of the customer', null=True, blank=True, max_length=50)
    house_name = models.CharField('House name', null=True, blank=True, max_length=50)
    street = models.CharField('Street', null=True, blank=True, max_length=50)
    city = models.CharField('City', null=True, blank=True, max_length=50)
    district = models.CharField('District', null=True, blank=True, max_length=50)
    pin = models.CharField('Pin', max_length=10, null=True, blank=True,)
    mobile_number = models.CharField('Mobile Number', max_length=15, null=True, blank=True)
    land_line = models.CharField('Land Line', max_length=25, null=True, blank=True)
    customer_id = models.CharField('Customer Id(Email id)', max_length=75)

    def __unicode__(self):
        return "customer - "+ str(self.customer_name)

    # def save(self, *args, **kwargs):
    #     profile = self.user.userprofile_set.all()
    #     if len(profile) == 0:
    #         profile = UserProfile.objects.create(user = self.user)
    #     super(Customer, self).save(*args, **kwargs)


    class Meta:

        verbose_name = 'Customer'
        verbose_name_plural = 'Customer'

class TransportationCompany(models.Model):

    company_name = models.CharField('Company Name', null=True, blank=True, max_length=50)

    def __unicode__(self):

        return self.company_name

    class Meta:

        verbose_name = 'Transportation Company'
        verbose_name_plural = 'Transportation Company'

class OwnerCompany(models.Model):

    company_name = models.CharField('Company Name', max_length=100)
    logo = models.FileField('Logo', upload_to = "uploads/logo/", null=True, blank=True)

    def __unicode__(self):

        return self.company_name

    class Meta:

        verbose_name = 'Owner Company'
        verbose_name_plural = 'Owner Company'

smartbook/web/templates/add_new_company.html
<div style='display:none' id="add_company">
    <div id='add_new_designation' style='padding:10px; background:#fff;'>
        <div class="sign_box">
            <div class="row-fluid">
                <div class="span12 sign_mid">
                    <span>
                        <form action="" id="register" name="register" method="post" class="reg_sec">
                            <div class="formrow">
                                <div class="formtext">
                                    <label>Company Name</label>
                                </div>
                                <div class="forminput">  
                                    <input type="text" name="company_name" ng-model="company_name" />
                                </div>  
                            </div>
                            <div align="center">
                                <p ng-show="error_flag" class="error_message">[[message]]</p>
                                <input name="submit" type="button" value="Add" ng-click="add_new_company()">
                                <input name="cancel" type="button" value="Cancel" ng-click="close_popup()">
                            </div>
                        </form>                        
                    </span>
                </div>
            </div>    
        </div>
        <div class="clearfix"></div>
    </div>
</div>

smartbook/web/templates/add_new_customer.html
<div style='display:none' id="add_customer">
    <div id='add_new_customer' style='padding:10px; background:#fff;'>
        <div class="sign_box">
            <div class="row-fluid">
                <div class="span12 sign_mid">
                    <form action="" id="register" name="register" method="post" class="reg_sec">
                        {% csrf_token %}
                        <div class="control">
                            <label>Customer Name</label>
                            <input name="name" type="text" ng-model="customer_name"/>
                        </div>
                        
                        <div class="control">
                            <label>House Name</label>
                            <input name="house" type="text" ng-model="house_name"/>
                        </div>
                        <div class="control">
                            <label>Street</label>
                            <input name="street" type="text" ng-model="street"/>
                        </div>
                        <div class="control">
                            <label>City</label>
                            <input name="city" type="text" ng-model="city"/>
                        </div>
                        <div class="control">
                            <label>District</label>
                            <input name="district" type="text" ng-model="district"/>
                        </div>
                        <div class="control">
                            <label>Pin</label>
                            <input name="pin" type="text" ng-model="pin" />
                        </div>
                        <div class="control">
                            <label>Mobile</label>
                            <input name="mobile" type="text" ng-model="mobile" />
                        </div>
                        <div class="control">
                            <label>Land Line</label>
                            <input name="phone" type="text" ng-model="land_line"/>
                        </div>
                        <div class="control">
                            <label>Email Id</label>
                            <input name="email" type="text" ng-model="email_id" />
                        </div>
                        <div align="center">
                            <p ng-show="error_flag" class="error_message">[[error_message]][[message]]</p>
                            <input name="submit" type="button" value="Add" ng-click="add_new_customer()">
                            <input name="cancel" type="button" value="Cancel" ng-click="close_popup()">
                            
                        </div>
                    </form>                        
                </div>
            </div>    
        </div>
        <div class="clearfix"></div>
    </div>
</div>

smartbook/web/templates/add_new_vendor.html
<div style='display:none' id="add_vendor">
    <div id='add_new_vendor' style='padding:10px; background:#fff;'>
        <div class="sign_box">
            <div class="row-fluid">
                <div class="span12 sign_mid">
                    <form action="" id="register" name="register" method="post" class="reg_sec">
                        {% csrf_token %}
                        <div class="control">
                            <label>Vendor Name</label>
                            <input name="name" type="text" ng-model="vendor_name"/>
                        </div>
                        <div class="control">
                            <label>Contact Person</label>
                            <input name="contact_person" type="text" ng-model="contact_person"/>
                        </div>
                        <div class="control">
                            <label>House Name</label>
                            <input name="house" type="text" ng-model="house_name"/>
                        </div>
                        <div class="control">
                            <label>Street</label>
                            <input name="street" type="text" ng-model="street"/>
                        </div>
                        <div class="control">
                            <label>City</label>
                            <input name="city" type="text" ng-model="city"/>
                        </div>
                        <div class="control">
                            <label>District</label>
                            <input name="district" type="text" ng-model="district"/>
                        </div>
                        <div class="control">
                            <label>Pin</label>
                            <input name="pin" type="text" ng-model="pin" />
                        </div>
                        <div class="control">
                            <label>Mobile</label>
                            <input name="mobile" type="text" ng-model="mobile" />
                        </div>
                        <div class="control">
                            <label>Land Line</label>
                            <input name="phone" type="text" ng-model="land_line"/>
                        </div>
                        <div class="control">
                            <label>Email Id</label>
                            <input name="email" type="text" ng-model="email_id" />
                        </div>
                        <div align="center">
                            <p class="error_message">[[validation_error]]</p>
                            <input name="submit" type="button" value="Add" ng-click="add_new_vendor()">
                            <input name="cancel" type="button" value="Cancel" ng-click="close_popup()">
                        </div>
                    </form>                        
                </div>
            </div>    
        </div>
        <div class="clearfix"></div>
    </div>
</div>

smartbook/web/templates/base.html
<!DOCTYPE html>
<html ng-app="smartbook" xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<title>{% block title %}{% endblock title %} | SmartBook </title>
		<link rel="shortcut icon" href="/static/images/logo_icon.png" type="image/x-icon" />

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% block facebook_meta %}
		{% endblock facebook_meta %}
		<!-- linked in meta tag -->
		<meta name="p:domain_verify" content="ce218e9f8daf32477bcc841eb40ced8f"/>
		<!-- Bootstrap -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css" />
		<link rel="stylesheet" href="/static/css/style.css" type="text/css" />
		<!-- Calendar css -->
		<link rel="stylesheet" href="/static/css/calendar/datepicker_bootstrap.css">

		<script src="/static/js/lib/jquery-1.9.1.js"></script>
		<!--  Angularjs -->
		<script src="/static/js/angular_app/lib/angular/angular.js"></script>
	    <script src="/static/js/angular_app/lib/angular/angular-resource.js"></script>
	  	<script src="/static/js/angular_app/app.js"></script>
	    <script src="/static/js/angular_app/services.js"></script>
	    <script src="/static/js/angular_app/directives.js"></script>
	  	<script src="/static/js/angular_app/controllers.js"></script>
	  	<!-- Mootools -->
	  	<script src="/static/js/mootools/lib/mootools-core-1.4.5-full-compat-yc.js"></script>
		<script src="/static/js/mootools/lib/mootools-more-1.4.0.1.js"></script>
		<script src="/static/js/mootools/common.js"></script>
		
		<!-- Calendar js-->

		<script src="/static/js/mootools/calendar/Picker.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Attach.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Date.js" type="text/javascript"></script>
		<script src="/static/js/mootools/calendar/Picker.Date.Range.js" type="text/javascript"></script>
		
	  	
	    <script>

			window.addEvent('domready', function(){
				// new Picker.Date($$('#date'), {
				// 	timePicker: false,
				// 	positionOffset: {x: 5, y: 0},
				// 	pickerClass: 'datepicker_bootstrap',
				// 	useFadeInOut: !Browser.ie
				// });
				
			});

		</script>

		{% block extrahead %}
		{% endblock extrahead %}
		
	</head>
	<body id="{% block body_id %}base{% endblock %}"  {% block controller %}{% endblock controller %}>
		
		<div class="container" >

			{% block header %}
				{% include 'header.html' %}
			{% endblock header %}
			<div id="overlay"></div>
			<div id="dialogue_popup_container">
				<div id="dialogue_popup">
					<a href="" class="close_pop" ng-click="hide_popup()"></a>
					{% block dialogue_popup %}
	                	
	                {% endblock %}
					<p class="message"></p>

				</div>
			</div>

			<div class="content">
				{% block content %}
				{% endblock content %}
			</div>		
			<div>
			{% block footer %}
				{% include 'footer.html' %}
			{% endblock footer %}
			</div>
		</div>
	</body>
</html>

smartbook/web/templates/edit_user.html
{% extends 'base.html' %}
{% block title %} 
	{% if user_type == 'vendor' %} 
		Edit Vendor
	{% endif %}
	{% if user_type == 'Salesman' %} 
		Edit Salesman
	{% endif %}
	{% if user_type == 'customer' %} 
		Edit Customer
	{% endif %}
{% endblock title %}
{% block body_id %} edit_{{user_type}} {% endblock body_id %}

{% block content %}

<div id="main-title">
	<div class="alert alert-info" align="Center">
		
		{% if user_type == 'vendor' %} 
			Edit Vendor
		{% endif %}
		{% if user_type == 'Salesman' %} 
			Edit Salesman
		{% endif %}
		{% if user_type == 'customer' %} 
			Edit Customer
		{% endif %}
	</div>
</div>

<div class="form_container">
	{% if user_type == 'customer' %}
		<form name="staffadd" method="post" action="{% url 'edit_user' user_type=user_type user_id=profile.id%}">
	{% else %}
		<form name="staffadd" method="post" action="{% url 'edit_user' user_type=user_type user_id=profile.user.id%}">
	{% endif %}
		{% csrf_token %}
		<p class="error_message">{{ message }}</p>
		<div class="control">
			<label>Name</label>
			{% if user_type == 'customer' %}
				<input name="name" type="text" value="{{profile.customer_name}}" />
			{% else %}
				<input name="name" type="text" value="{{profile.user.first_name}}" />
			{% endif %}
		</div>
		{% if user_type == 'vendor' %}
			<div class="control">
				<label>Contact Person</label>
				<input name="contact_person" type="text" value="{{profile.user.vendor_set.all.0.contact_person}}" />
			</div>
		{% endif %}
		{% if user_type == 'Salesman' %}
			<div class="control">
				<label>Username</label>
				<input name="username" type="text" value="{{profile.user.username}}" readonly />
			</div>
		{% endif %}
		
		<div class="control">
			<label>House Name</label>
			<input name="house" type="text" value="{{profile.house_name}}" />
		</div>
		<div class="control">
			<label>Street</label>
			<input name="street" type="text" value="{{profile.street}}" />
		</div>
		<div class="control">
			<label>City</label>
			<input name="city" type="text" value="{{profile.city}}" />
		</div>
		<div class="control">
			<label>District</label>
			<input name="district" type="text" value="{{profile.district}}" />
		</div>
		<div class="control">
			<label>Pin</label>
			<input name="pin" type="text" value="{{profile.pin}}" />
		</div>
		<div class="control">
			<label>Mobile</label>
			{% if user_type == 'customer' %}
				<input name="mobile" type="text" value="{{profile.mobile_number}}" />
			{% else %}
				<input name="mobile" type="text" value="{{profile.mobile}}" />
			{% endif %}
		</div>
		<div class="control">
			<label>Land Line</label>
			<input name="phone" type="text" value="{{profile.land_line}}" />
		</div>
		<div class="control">
			<label>Email Id</label>
			{% if user_type == 'customer' %}
				<input name="email" type="text" value="{{profile.customer_id}}" />
			{% else %}
				<input name="email" type="text" value="{{profile.email_id}}" />
			{% endif %}
		</div>
		<div class="control">
			<label>&nbsp; &nbsp; </label>
			<p class="error_message"> {{error_message}} </p> 
			<input type="submit" value="Submit" class="btn btn-info">
		</div>
	</form>
</div>

{% endblock content %}

smartbook/web/templates/footer.html
<footer>
	<p> {{ owner_company_name }} </p>
</footer>

smartbook/web/templates/header.html
<div class="menu_header">
	<div class="logo">
		<img src="/static/images/Logo.png" >
	</div>
	<div class="menu_div">
		{% if user.is_authenticated %}
			<ul>
				<li class="menu"> <img src="/static/images/user.png" width="24px" >
					<span class="user_name"> 
						{% if user.is_authenticated %}
							{% if user.first_name %}
								{{user.first_name}} {{user.last_name}} 
							{% else %} 
								{{user.username}}
							{% endif %} 
						{% endif %}
					</span>
					<ul>
						<li> <a href="{% url 'backup' %}"> DB Backup </a> </li>
						<li> <a href="{% url 'clear_backup' %}"> Backup Folder </a> </li>
						<li> <a href="{% url 'users' user_type='vendor' %}"> Vendors </a> </li>
						
						<li> <a href="{% url 'users' user_type='Salesman' %}"> Sales Men </a> </li> 

						<li> <a href="{% url 'users' user_type='customer'  %}"> Customers </a> </li>
						<li> <a href="{% url 'logout' %}"> Logout </a> </li>
						<li> <a href="{% url 'reset_password' user_id=user.id %}"> Reset password </a> </li>
					</ul>
				</li>
				<li class="menu"> <a href=""> Inventory </a> 
					<ul> 
						<li> <a href="{% url 'item_list' %}"> Items </a> </li>
						<li> <a href="{% url 'stock' %}"> Stock </a> </li>
						<li> <a href="{% url 'opening_stock' %}"> Opening Stock </a> </li>
						
					</ul>
				</li>
				<li class="menu"> <a href=""> Purchase </a> </a> 
					<ul> 
						<li> <a href="{% url 'purchase' %}"> New Entry </a> </li>
						<li> <a href="{% url 'edit_purchase' %}"> Edit Purchase </a> </li>
						<li> <a href="{% url 'purchase_return' %}"> Purchase Return </a> </li>
						<li> <a href="{% url 'vendor_accounts' %}"> Vendor Accounts </a> </li>
					</ul>
				</li>
				<li class="menu"> <a href=""> Sales </a>
					<ul>
						<li><a href="{% url 'create_quotation' %}"> Quotation</a></li>
						<li><a href="{% url 'create_delivery_note' %}"> Delivery Note</a></li>
						<li><a href="{% url 'direct_delivery_note' %}"> Direct Delivery Note</a></li>
						<li><a href="{% url 'create_sales_entry' %}"> Sales (Qn/ DN)</a></li>
						<li> <a href="{% url 'sales' %}"> Direct Sales </a> </li>
						<li> <a href="{% url 'receipt_voucher' %}"> Receipt Voucher</a> </li>
						<li> <a href="{% url 'return_entry' %}"> Return Entry</a> </li>
						<li> <a href="{% url 'edit_sales_invoice' %}"> Edit Sales Invoice </a> </li>
						<li> <a href="{% url 'edit_quotation' %}"> Edit Quotation</a> </li>
						<li><a href="{% url 'edit_delivery_note' %}"> Edit Delivery Note </a> </li>
					</ul>
				</li>
				<li class="menu"> <a href="{% url 'new_expense' %}"> Expenses </a> 
					<ul>
						<li><a href="{% url 'new_expense' %}">Expenses</a></li>
						<li><a href="{% url 'new_expense_head' %}"> Expense Head</a></li>
						<li><a href="{% url 'edit_expense' %}">Edit Expenses</a></li>
					</ul>
				</li>

				<li class="menu last"> <a href=""> Reports </a>
					<ul>
						<li><a href="{% url 'daily_report' %}"> Daily Reports </a> </li>
						<li><a href="{% url 'sales_reports' %}"> Sales </a> </li>
						<li><a href="{% url 'sales_return_report' %}"> Sales Return</a> </li>
						<li><a href="{% url 'stock_reports' %}"> Stock </a> </li>
						<li><a href="{% url 'purchase_reports' %}"> Purchase </a> </li>
						<li><a href="{% url 'purchase_return_report' %}"> Purchase Return </a> </li>
						<li><a href="{% url 'expense_report' %}"> Expense Report </a> </li>
						<li><a href="{% url 'vendor_accounts_report' %}"> Vendor Accounts </a> </li>
					</ul>
				</li>
			</ul>
		{% endif %}
	</div>
</div>

smartbook/web/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title%}
{% block content %}
	{% if user.is_authenticated %}	
		<h1 class="welcome"> Welcome to {{owner_company_name}} </h1>

	{% else %}
	
		<div class="login">
			<div class="div_header">
				Login
			</div>
			<div class="login_form_container">
				<form name="login" method="post" action="{% url 'login' %}">
					{% csrf_token %}
					<p> <label for="username" >Username:</label> <input type="text" name="username" /></p>
					<p> <label for="password">Password : </label><input type="password" name="password" /></p>
					<p> {{message}} </p>
					<p> <input type="submit" name="submit" value="Login" />
				</form>
			</div>
			<div class="clear"></div>
		</div>
	{% endif %}
{% endblock content %}

smartbook/web/templates/register_user.html
{% extends 'base.html' %}
{% block title %} 
	{% if user_type == 'Salesman' %} 
		New Salesman
	{% endif %}
	{% if user_type == 'vendor' %} 
		New Vendor
	{% endif %}
	{% if user_type == 'customer' %} 
		New Customer
	{% endif %}
{% endblock title %}
{% block body_id %} new_{{user_type}} {% endblock body_id %}
{% block content %}

<div id="main-title">
	<div class="alert alert-info" align="Center">
		{% if user_type == 'Salesman' %} 
			New Salesman
		{% endif %}
		{% if user_type == 'vendor' %} 
			New Vendor
		{% endif %}
		{% if user_type == 'customer' %} 
			New Customer
		{% endif %}
	</div>
</div>
<div class="form_container">
	{% if user_type == 'customer' %}
		<form name="staffadd" method="post" action="{% url 'create_customer'%}">
	{% else %}
		<form name="staffadd" method="post" action="{% url 'register_user' user_type=user_type %}">
	{% endif %}
			{% csrf_token %}
			<div class="control">
				<p class="error_message">{{ message }}</p>
				<p class="error_message"> {{error_message}} </p> 
			</div>
			<div class="control">
				<label>Name</label>
				<input name="name" type="text" value="{{name.0}}" />
			</div>
			{% if user_type == 'vendor' %}
				<div class="control">
					<label>Contact Person</label>
					<input name="contact_person" type="text" value="{{contact_person.0}}" />
				</div>
			{% endif %}
			{% if user_type == 'Salesman' %}

				<div class="control">
					<label>Username</label>
					<input name="username" type="text" value="{{username.0}}" />
				</div>

				<div class="control">
					<label>Password</label>
					<input name="password" type="password" value="{{password.0}}" />
				</div>
				
			{% endif %}
			
			<div class="control">
				<label>House Name</label>
				<input name="house" type="text" value="{{house.0}}" />
			</div>
			<div class="control">
				<label>Street</label>
				<input name="street" type="text" value="{{street.0}}" />
			</div>
			<div class="control">
				<label>City</label>
				<input name="city" type="text" value="{{city.0}}" />
			</div>

			<div class="control">
				<label>District</label>
				<input name="district" type="text" value="{{district.0}}" />
			</div>
			<div class="control">
				<label>Pin</label>
				<input name="pin" type="text" value="{{pin.0}}" />
			</div>
			<div class="control">
				<label>Mobile</label>
				<input name="mobile" type="text" value="{{mobile.0}}" />
			</div>
			<div class="control">
				<label>Land Line</label>
				<input name="phone" type="text" value="{{phone.0}}" />
			</div>
			<div class="control">
				<label>Email Id</label>
				<input name="email" type="text" value="{{email.0}}" />
			</div>
			<div class="control">
				<label> </label>
				
				<input type="submit" value="Submit" class="btn btn-info">
			</div>
		</form>
</div>

{% endblock content %}

smartbook/web/templates/reset_password.html
{% extends 'base.html' %}
{% block title %} 
	Reset Password
{% endblock title %}
{% block body_id %} reset_password {% endblock body_id %}
{% block content %}

<div id="main-title">
	<div class="alert alert-info" align="Center">
		Reset Password
	</div>
</div>
<div class="form_container">
	<form name="staffadd" method="post" action="{% url 'reset_password' user_id=user_id %}">
		{% csrf_token %}
		{{ message }}
		
		<div class="control">
			<label>New Password</label>
			<input name="password" type="password" value="" />
		</div>

		<div class="control">
			<label> </label>
			<p class="error_message"> {{error_message}} </p> 
			<input type="submit" value="Submit" class="btn btn-info">
		</div>
	</form>
</div>

{% endblock content %}